import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import LoginPage from './pages/login';
import AdminPage from './pages/admin';
import InventoryPage from './pages/InventoryPage';
import Redirector from './pages/Redirector';
import AuthGuard from './components/AuthGuard';
ReactDOM.createRoot(document.getElementById('root')).render(_jsx(React.StrictMode, { children: _jsx(BrowserRouter, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(Redirector, {}) }), _jsx(Route, { path: "/login", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "/admin", element: _jsx(AuthGuard, { children: _jsx(AdminPage, {}) }) }), _jsx(Route, { path: "/inventory", element: _jsx(AuthGuard, { children: _jsx(InventoryPage, {}) }) })] }) }) }));
